platform :ios, '14.1'
use_frameworks!
inhibit_all_warnings!

def testing_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'Sourcery'
  pod 'SwiftFormat/CLI'
end

target 'PhongKMMIC' do
  # UI
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'SkeletonUI'
  pod 'SwiftUIPager'

  # Storage
  pod 'KeychainAccess'

  # Tools
  pod 'Firebase/Crashlytics'
  pod 'IQKeyboardManagerSwift'
  pod 'NimbleExtension', :git => 'https://github.com/nimblehq/NimbleExtension', :branch => 'master'
  pod 'R.swift'
  pod 'Factory'
  pod 'FlowStacks'
  pod 'KMPNativeCoroutinesCombine', '0.12.6'  # Combine implementation

  # Development
  pod 'SwiftLint'
  pod 'Wormholy', :configurations => ['Debug Staging', 'Debug Production']
  pod 'xcbeautify'

  # KMM
  pod 'shared', :path => '../shared'

  target 'PhongKMMICTests' do
    inherit! :search_paths
    testing_pods
  end

  target 'PhongKMMICKIFUITests' do
    inherit! :search_paths
    testing_pods
    pod 'KIF', :configurations => ['Debug Staging', 'Debug Production']
    pod 'KIF/IdentifierTests', :configurations => ['Debug Staging', 'Debug Production']
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
