name: Build and Test

on:
  pull_request

jobs:
  iOS_automatic_pull_request_review:
    name: Automatic Pull Request Review - iOS App
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: bunlderCache
        with:
          path: iosApp/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Bundle install
        working-directory: iosApp
        run: bundle install --path vendor/bundle

      - name: Cache Pods
        uses: actions/cache@v3
        id: cocoapodCache
        with:
          path: iosApp/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods Dependencies
        working-directory: iosApp
        run: bundle exec pod install

      - name: Build and Test
        working-directory: iosApp
        run: bundle exec fastlane buildAndTest

      - name: Clean up previous code coverage report
        working-directory: iosApp
        run: bundle exec fastlane cleanUpOutput

      - name: Review pull request by Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
