name: iOS Automatic Code Review

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  shared_test:
      name: Running tests in Shared module
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: shared
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Konfig Properties
        env:
          KMM_KONFIG_PROPERTIES: ${{ secrets.KMM_KONFIG_PROPERTIES }}
        run: |
          touch ../buildKonfig.properties
          echo $KMM_KONFIG_PROPERTIES | base64 --decode > ../buildKonfig.properties

      - name: Running tests
        run: |
          cd ..
          ./gradlew clean shared:test

  iOS_automatic_pull_request_review:
    name: Automatic Pull Request Review - iOS App
    runs-on: macos-latest
    defaults:
        run:
          working-directory: iosApp
    steps:
      - name: Set up JAVA 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        id: bunlderCache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Bundle install
        run: bundle install --path vendor/bundle

      - name: Setup Konfig Properties
        env:
          KMM_KONFIG_PROPERTIES: ${{ secrets.KMM_KONFIG_PROPERTIES }}
        run: |
          touch ../buildKonfig.properties
          echo $KMM_KONFIG_PROPERTIES | base64 --decode > ../buildKonfig.properties

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate KMM frameworks for Cocoapods
        run: |
          cd ..
          ./gradlew generateDummyFramework

      - name: Cache Pods
        uses: actions/cache@v3
        id: cocoapodCache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods Dependencies
        run: bundle exec pod install

      - name: Build and Test
        run: bundle exec fastlane buildAndTest

      - name: Run iOS Danger
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'iosApp/Gemfile'
          install_path: 'iosApp/vendor/bundle'
          danger_file: 'iosApp/Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
